### PR TITLE
make the database and .env cookiecutter connection more clear

### PR DESCRIPTION
**Pull request by NathanQ**
in regards to issues #490, #270 and #710

### CODE REVIEW

**Comment by webyneter** [comment]
Overall, the intent is positive IMO, however for consistency we would need to migrate our whole infrastructure to python scripts and, therefore, other existing shell scripts also should be reviewed. Although it's possible to switch to python-based scripting, to the best of my knowledge shell scripts are the industry standard (ideally, POSIX-compliant variants of those) thanks to the omnipresence of the latter.

**Comment by luzfcb** [comment]
POSTGRES_PASSWORD and POSTGRES_USER only is used because is required by [docker-entrypoint.sh](https://github.com/docker-library/postgres/blob/972294a377463156c8d61297320c872fc7d370a9/9.6/docker-entrypoint.sh) script of Postgresql docker image

**Comment by NathanQ** [comment]
Thanks for the feedback @webyneter. I feel there is a need to resemble the [Django docs database setting](https://docs.djangoproject.com/en/1.11/ref/settings/#databases) to allow settings to be more easily managed.

Basis for PR:
#270 and #490
```
# base.py
DATABASES = {
    'default': env.db('DATABASE_URL', default='postgres://{% if cookiecutter.windows == 'y' %}localhost{% endif %}/{{cookiecutter.project_slug}}'),
}
```
and
```
# example.env
POSTGRES_PASSWORD=mysecretpass
POSTGRES_USER=postgresuser
```
If the env file is to be used, it seems like the database setting should include them so the env file can be used to set them. If it's to be rewritten to use the env settings, it's not very cookiecutter.

#710 
Adding `CONN_MAX_AGE` to the cookiecutter allows for this to be an accessible setting.

**Comment by luzfcb** [comment]
By default, cookiecutter-django does not use the .env file, ( https://12factor.net/config ). It is only used if you choose to use docker, and only to automate the creation of environment variables during the build of the docker images.


About CONN_MAX_AGE, this can be included with something like this
```python
DATABASES = {
    'default': env.db('DATABASE_URL', default='postgres://{% if cookiecutter.windows == 'y' %}localhost{% endif %}/{{cookiecutter.project_slug}}'),
}
DATABASES['default']['ATOMIC_REQUESTS'] = True
DATABASES['default']['CONN_MAX_AGE'] = env.int("DJANGO_CONN_MAX_AGE", default=0)
```

**Comment by NathanQ** [comment]
@luzfcb Fair enough and good point. Fwiw, env files are used by those who don't yet use docker.

The primary point of the pr is to address the mentioned issues. The issues are rooted in the bit of obfuscation between cookiecutter-django's base settings, its corresponding example.env and those of Django docs examples along with available settings. Changing from an url to an object structure to mirror "official" doc examples makes it straightforward to those who rely on documentation.

**Comment by japrogramer** [comment]
I know this thread is about making .env file more clear for database settings .. but I don't think there should be a .env file at all for docker deployments. 
Hear me out.
If a user really needs to set an enviorment variable it can be done from a compose file.
Now for sensitive stuff, I believe that stuff doesn't even belong in environment variables the reason
for this believe: too often are these settings logged out to file and than you have your secrets scattered everywhere.. now you have too worry about sanitizing your logs and even worse securing your logs.
These is my solution, I have gone and removed the .env file, and only rely on docker secrets. And I don't even use environment variables, because they too often get logged by programs, and if you are keeping logs that is a security risk. The file that i read in as a secret is structured like a json object so i can easily parse in python. Each container has a different set of secrets and they only see what they need to see. I do not have the secrets stored in plain txt anywhere instead I archive the swarm dir in docker which stores encrypted secrets.
#on a manager node
```
$docker secret create my_secret -
$ tee -
#mind you, my secrets are mounted into my containers from within their respective compose file
$systemctl stop docker.service 
$tar czpvf swarm-dev.tar.gz /var/lib/docker/swarm/
```
than i rsync that file over an encrypted pipe back home
and when i need to restore my secrets i do 
```
$systemctl stop docker.service 
$rm -fR /var/lib/docker/swarm
$tar xzpvf swarm-dev.tar.gz -C /var/lib/docker/swarm/
$systemctl start docker.service 
$docker swarm init --force-new-cluster
$ tee -
#Now all my secrets are back, and available to my swarm. But only to those containers that have been given permission on a per secret basis.
```

**Comment by webyneter** [comment]
> I feel there is a need to resemble the Django docs database setting to allow settings to be more easily managed.

@NathanQ yes, I agree now. 

@luzfcb `POSTGRES_*` envs are also widely used in backup/restore shell scripts as well as the docs. By the way, @NathanQ, the PR doesn't address all these occurrences -- it would be great if you'd fix this project-wide.

**Comment by jayfk** [comment]
@webyneter already mentioned this: The environment variables are used all over the project in all kinds of different places. A pull request needs to address this properly.

**Pull request closed without merging**
