### PR TITLE
Can't use AWS_STORAGE_BUCKET_NAME until post_setup.

### PR DESCRIPTION
**Pull request by jeffcjohnson**
With old code:
STATIC_URL: "https://s3.amazonaws.com/&lt;Value default: None&gt;/"

With new code:
STATIC_URL: "https://s3.amazonaws.com/mybucket/"

### CODE REVIEW

**Comment by jeffcjohnson** [comment]
This solved part of my problem but set STATIC_URL too late for at least one library I was using.  I'm closing this until I figure out more.

**Comment by jeffcjohnson** [comment]
Replacing the old code with the following seems to do the trick.  I'm not sure why django-configuration Value is doing late or lazy evaluation of the variable but it isn't working well for me.

STATIC_URL = 'https://s3.amazonaws.com/%s/' % os.environ.get('DJANGO_AWS_STORAGE_BUCKET_NAME')

Does anyone have any advice here?

**Comment by jeffcjohnson** [comment]
This is a duplicate of #121.

**Comment by luzfcb** [comment]
@jeffcjohnson You could test with this:
https://github.com/pydanny/cookiecutter-django/blob/24f544083e61db34c457ae18abe58c19041ec1af/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.project_name%7D%7D/config/settings.py#L362-L368

and/or this:

https://github.com/pydanny/cookiecutter-django/pull/201/files

**Pull request closed without merging**
