### PR TITLE
Fix Docker configuration for Gitlab CI

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**
[//]: # (Thank you for helping us out: your efforts mean great deal to the project and the community as a whole!)

[//]: # (Before you proceed:)

[//]: # (1. Make sure to add yourself to `CONTRIBUTORS.rst` through this PR provided you're contributing here for the first time)
[//]: # (2. Don't forget to update the `docs/` presuming others would benefit from a concise description of whatever that you're proposing)

## Description

[//]: # (What's it you're proposing?)

* Just missing the services I believe according to @rocode?

This should provide the temporary fix for GitLab CI #2549
 

## Rationale

[//]: # (Why does the project need that?)

Quick fix for those using GitLab CI

## Use case(s) / visualization(s)

* I'm hoping to just completely eradicate the need for this setup with a follow-up PR for completely non-Docker approach on CI that supports celery, too.

[//]: # ("Better to see something once than to hear about it a thousand times.")

### CODE REVIEW

**Comment by Andrew-Chen-Wang** [comment]
Thanks @rocode! Also, I've configured Travis to use a non Docker approach which cuts down the CI runtime by 1.5 minutes. Do you mind if I ping you again so that you can test that PR (when I find the time to copy and paste the config file and rewrite the tests) on Gitlab CI?

**Comment by rocode** [comment]
> 
> 
> Thanks @rocode! Also, I've configured Travis to use a non Docker approach which cuts down the CI runtime by 1.5 minutes. Do you mind if I ping you again so that you can test that PR (when I find the time to copy and paste the config file and rewrite the tests) on Gitlab CI?

Sounds good! Our current CI is about ~5 minutes, so that will be **very** appreciated.

**Comment by Andrew-Chen-Wang** [comment]
@rocode Ah, I might as well get you started. My current Travis configuration is extremely wacky at the moment, but the gist of it, in Travis, is to use the built-in services. To avoid the entire Docker thing, you just need to add the environment variables that are in the .envs directory.

AFAIK in my config, that would be:
```
- USE_DOCKER="no"
    - TEST_TWO_SIDED_PROPOSING_NRMP_ALGO_X_TIMES=100
    - DATABASE_URL="postgres:///mydatabase"
    - REDIS_URL="redis://localhost:6379/0"
    - CELERY_BROKER_URL="redis://localhost:6379/0"
```
and my services are Postgres and Redis.

For celery, use this: `- celery multi start beat worker -A config.celery_app --pool=solo`

And your script should be `pytest`.

**Comment by Andrew-Chen-Wang** [comment]
@rocode Ah, I might as well get you started. My current Travis configuration is extremely wacky at the moment, but the gist of it, in Travis, is to use the built-in services. To avoid the entire Docker thing, you just need to add the environment variables that are in the .envs directory.

AFAIK in my config, that would be:
```
- USE_DOCKER="no"
- DATABASE_URL="postgres:///mydatabase"
- REDIS_URL="redis://localhost:6379/0"
- CELERY_BROKER_URL="redis://localhost:6379/0"
```
and my services are Postgres and Redis.

For celery, use this: `- celery multi start beat worker -A config.celery_app --pool=solo`

And your script should be `pytest`.

**Pull request merged**
