### PR TITLE
Feature/database url

### PR DESCRIPTION
**Pull request by berndca**
This is my second pull requests related to issue #136. It appears that username and password are required in the database url. I have added default values for development and a check to ensure that a password other than 'blank' is used. Please share your feedback and concerns.

Thanks, Bernd

### CODE REVIEW

**Comment by theskumar** [comment]
I think the current implementation with the updated README [1] is clear enough on how to use dj-database url. Generally when you install a postgres, the database you are connecting doesn't require a password. 80% use case. I never required one during development. The database creation using command line has always been just `createdb <project_name>` command.

[1] https://github.com/pydanny/cookiecutter-django#getting-up-and-running

I would like to close this issue without doing anything. @pydanny @luzfcb Thoughts?

**Comment by theskumar** [comment]
Update: probably we can just override the `DATABASE_URL` to be a secretValue or an empty value and force user to set is explicitly. (Not required if you have deployed on Heroku) 

PS: But not sure if `values.DatabaseURL()` can be a secretValue().

**Comment by philippeluickx** [comment]
So I tried setting secretValue() because I am using a password to access the DB. Things don't really work out, as I get complaints about database needing a "default".
Isn't it generally a bad idea to use a password in your conf?

**Comment by theskumar** [comment]
> Isn't it generally a bad idea to use a password in your conf?

Yes it is. 

You'll still need to use `values.DatabaseURL()` and not `secretValue()` for `DATABASE` setting as under the hood. `dj-database-url` [1] is used to parse the database url. 

[1]
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/requirements/base.txt#L8, 
https://github.com/kennethreitz/dj-database-url
https://django-configurations.readthedocs.org/en/0.5/values/#configurations.values.DatabaseURLValue

**Comment by philippeluickx** [comment]
Which I am, but somehow not feeling happy with it...

**Comment by theskumar** [comment]
As such there is no alternative to it, unless you want to open up an issue at https://github.com/jezdez/django-configurations/. 

This has to be improvement in `values.DatabaseURL()` to accept something like `required=True`. I haven't tested what happens if you keep it empty in `production.py`

**Comment by philippeluickx** [comment]
Opened https://github.com/jezdez/django-configurations/issues/95

**Comment by theskumar** [comment]
> Hence, is it somehow possible to include an environment variable when using values.DatabaseURL()

@philippeluickx the DatabaseURL() can read from the environment variable. The only different between DatabaseURL and SecretValue is that you declare a SecretValue() is the property becomes a required property and django won't start if that value is missing in environment variable. 

What we want is a way to make DatabaseURL as required property and force user to set it via environment variable during production.

**Comment by philippeluickx** [comment]
Right, ok, now I get it. Will adapt the ticket, but less urgent in this case.
So if I get it right: I can leave the value empty and django-configurations will go and fetch it from the env vars?

**Comment by theskumar** [comment]
​Yes. The name of environment variable is `DATABASE_URL`​ it's added to
heroku by default when you add postgres database.

I believe the cause of confusion is all the things are implicit. :?

> Explicit is better than implicit. -- Zen of python

**Comment by philippeluickx** [comment]
You sir, made me smile!
Wondering which would be the best way to improve docs. In all honesty, I am trying to setup a new server and adopting best practices. Coming from Apache and lacking some nice up-to-date docs for Gunicorn.
Where to put environment vars in dev, prod,..?

Which leads back to this ticket, agreed we need more docs and explicity!

**Comment by theskumar** [comment]
@philippeluickx give https://github.com/theskumar/python-dotenv a shot. I've been using it in production servers and it works like charm. Happy to help with anything you are stuck.

**Comment by jwegis** [comment]
@philippeluickx @theskumar Another project to add to the mix: https://github.com/joke2k/django-environ

**Comment by luzfcb** [comment]
@jwegis @theskumar another: https://github.com/henriquebastos/python-decouple

**Comment by theskumar** [comment]
@luzfcb these all look like great projects. I think they should find a place in a wiki or somewhere else as alternatives to tools used in this project. 

django-environ and python-decouple would require not to use django-configuration. It seems `.env` support #197 is coming to django-configuration as well.

**Pull request closed without merging**
