### PR TITLE
 Pinning redis version to >=2.10.6, <3

### LINKED ISSUE #1868: New version of redis package is the cause of the Error
## What happened?

After redeploy, we got `redis==3.0.1` instead `redis==2.10.6`. So, when you try to work with cache for example, we got the exception: 

```
DataError: Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.
  File "django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "django/utils/decorators.py", line 134, in _wrapped_view
    result = middleware.process_request(request)
  File "django/middleware/cache.py", line 133, in process_request
    cache_key = get_cache_key(request, self.key_prefix, 'GET', cache=self.cache)
  File "django/utils/cache.py", line 360, in get_cache_key
    headerlist = cache.get(cache_key)
  File "django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "django_redis/cache.py", line 81, in get
    client=client)
  File "django_redis/client/default.py", line 202, in get
    value = client.get(key)
  File "redis/client.py", line 1207, in get
    return self.execute_command('GET', name)
  File "redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "redis/connection.py", line 659, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "redis/connection.py", line 124, in encode
    "byte, string or number first." % typename)
```
The problem exactly in the `redis==3.0.1`, as we may see there: https://stackoverflow.com/questions/53331405/django-compress-error-invalid-input-of-type-cachekey

It is because of this pkg sets in the `requiriments/base.txt` as `redis>=2.10.5  # https://github.com/antirez/redis`

## What should've happened instead?

All should work well

## Steps to reproduce

Just rebuild compose. 

(Ubuntu 18.04, Docker 17.05.0-ce)

### PR DESCRIPTION
**Pull request by Egregors**
Fixes #1868

### CODE REVIEW

**Comment by sunsong** [comment]
having the exact same issue, version 2.10.6 is good

**Comment by browniebroke** [comment]
Likely solved by #1870

**Comment by Egregors** [comment]
@browniebroke `django-redis` update to ver.: 4.10.0 does not solve all problems with `redis==3`.  See: #1868

**Comment by browniebroke** [comment]
Thanks for the contribution @Egregors!

**Comment by emilepetrone** [comment]
By chance, does this resolve the security issue with Redis? I just deployed a project to DigitalOcean with `redis==2.10.6` and `django-redis==4.9.0`. The docker config was not changed.

When I brought the instance up, DigitalOcean sent me the following email. If this is a separate issue, I can create a new ticket to dig into it further.

> This configuration that was reported to us can allow attackers to gain local access to your Droplet, as well as the ability to read, change, or destroy any data hosted in your Redis instance. This issue could result in severe security breaches, and we strongly urge you to take immediate action to secure your Redis instance. We have several resources available to help you secure your server.
> 
> For securing your Redis instance on Ubuntu, refer to this tutorial: https://do.co/redis-security-ubuntu-1404
> 
> For securing your Redis instance on CentOS, refer to this tutorial: https://do.co/redis-security-centos-7
> 
> We also offer Cloud Firewalls – available in all regions at no additional cost – to protect your Droplet from traffic attempting to access it without permission. Learn more about Cloud Firewalls here: https://do.co/intro-to-cloud-firewalls
> 
> The security of all systems in our network is extremely important to us and we strongly encourage you to review your configuration promptly.
> 
> Regards,
> 
> Trust & Safety
> 
> DigitalOcean Security

**Pull request merged**
