### PR TITLE
Letsencrypt for Docker

### PR DESCRIPTION
**Pull request by mjsisley**
Issue #471 (Also includes #575).
I pulled this from a project I am running in production. First time working with the cookiecutter template, so I may have missed something, but the three generation cases (w/ certbot and docker, w/o certbot, w/ certbot and w/o docker) worked by a manual test on my laptop (OS X).

- I am using docker-compose v1 syntax for volumes, does this need modification @jayfk ?
- There is extraneous space added in docker-compose.yml on generation through the cookiecutter template.
- Letsencrypt recently changes there name to certbot, not sure about naming.
- There may be a better approach to dhparams.pem generation, currently specifying in documentation and providing a warning.

Hope this is helpful to what you were working on @chrisdev. Caddyserver may be a better way to go.

### CODE REVIEW

**Comment by chrisdev** [comment]
@mjsisley i'm no docker expert but followed your docs and i generated the CSR request and certbot responded!
However, I had to change the last line of the ```compose/nginx/Dockerfile```
from:
````ADD /start.sh````
to:
````ADD start.sh /start.sh````

**Comment by mjsisley** [comment]
@chrisdev Missed that on the transfer from COPY to ADD and only tested the cookiecutter generation. as this arrangement has been working for me. Thanks for testing it and catching that!

Not sure where to cite sources... but this was mostly adopted from [here](http://www.automationlogic.com/using-lets-encrypt-and-docker-for-automatic-ssl/) with a few adjustments.

There may be a more concise way to accomplish the same thing. Caddyserver may be a better option as well. But maybe this is a starting point.

**Comment by chrisdev** [comment]
@mjsisley great job!

**Comment by mjsisley** [comment]
Thanks @chrisdev 
 
The bullet list above (extra whitespace, name certbot or letsencrypt or both, and docker-compose v1 volume syntax) could be addressed, but these aren't critical for it to work.

I think this is ready to merge if those can be adjusted later.

**Comment by pydanny** [comment]
@mjsisley I need to fix the author on the commits for this, since they ended up in my name. To do that, I need the email you used to register your SSH key on GitHub (probably your github personal mail).

**Comment by mjsisley** [comment]
@pydanny mjsisley@gmail.com

**Pull request merged**
