### PR TITLE
Allow to use a CDN with S3

### PR DESCRIPTION
**Pull request by tanoabeleyra**
[//]: # (Thank you for helping us out: your efforts mean great deal to the project and the community as a whole!)

[//]: # (Before you proceed:)

[//]: # (1. Make sure to add yourself to `CONTRIBUTORS.rst` through this PR provided you're contributing here for the first time)
[//]: # (2. Don't forget to update the `docs/` presuming others would benefit from a concise description of whatever that you're proposing)

## Description

[//]: # (What's it you're proposing?)
This PR allows using a CDN (e.g. AWS CloudFront) to serve the files stored in AWS S3. This is optional and backward-compatible, it will only be applied when specifying the environment variable `DJANGO_AWS_S3_CUSTOM_DOMAIN`.

## Rationale

[//]: # (Why does the project need that?)
It's really common to use S3 with CloudFront, this setting makes it easier to achieve that.

### CODE REVIEW

**Comment by Andrew-Chen-Wang** [comment]
You should add in that new environment variable to the .envs/.production/.django, writing a note there, adding some docs to the docs/settings.rst, and give a little more elaboration in the settings/production.py or the env file too.

**Comment by tanoabeleyra** [comment]
Hi @Andrew-Chen-Wang, thanks for the feedback. Considering that this variable is optional, should it go in `.envs/.production/.django`? For instance, `DJANGO_AWS_S3_REGION_NAME` is optional and it isn't in the envs file.

The idea is that if the user doesn't give any value to `DJANGO_AWS_S3_CUSTOM_DOMAIN` it should behave like it's currently doing in `master`.

**Comment by Andrew-Chen-Wang** [comment]
Ah I see. The "optional" justification makes sense.

**Comment by tanoabeleyra** [comment]
Is there anything else needed for this to be merged? (cc: @browniebroke)

**Comment by browniebroke** [comment]
Thanks for this!

> Is there anything else needed for this to be merged?

Nothing apart from me finding some spare time :)

**Comment by tanoabeleyra** [comment]
Hi @browniebroke. Sure, I understand, there's no rush actually, I just wanted to be sure that the changes looked ok to you.

Thanks for approving it!

**Pull request merged**
