### PR TITLE
Fix docker's letsencrypt renewal command

### PR DESCRIPTION
**Pull request by aleprovencio**

### CODE REVIEW

**Comment by aleprovencio** [comment]
Hello @pydanny! Can we have this merged up?

**Comment by aleprovencio** [comment]
Hello @pydanny ! Can we have this merged up?

**Comment by pydanny** [comment]
@jayfk, @webyneter, what do you think of this PR?

**Comment by webyneter** [comment]
@pydanny , seems like no weak spots out there.

**Pull request merged**
