### PR TITLE
Added django-robots integration

### PR DESCRIPTION
**Pull request by msamoylov**
Google seems to require robots.txt for new sites, otherwise it's not going to crawl them returning "Google couldn't crawl your site because we were unable to access your site's robots.txt file" in Google Search Console. Please refer to https://support.google.com/webmasters/answer/2409682 for the details.

This pull requests contains a working and tested integration of https://github.com/jazzband/django-robots/

### CODE REVIEW

**Comment by msamoylov** [comment]
I have to admit that I don't know how to fix that failing test.

**Comment by luzfcb** [comment]
Jinja2 has a different syntax to strip whitespace
http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

It will probably be something like: 
```django
{% if cookiecutter.use_robots == 'y' -%}

{%- endif %}
```

instead of

```django
{% if cookiecutter.use_robots == 'y' %}

{% endif %}
```

ps: the first time I had seen it, I thought it was a syntax error :-P

**Comment by msamoylov** [comment]
@luzfcb thanks man! That wasn't obvious for sure.

**Comment by pydanny** [comment]
Questions:

1. Why does this need to be in Cookiecutter Django? Shouldn't users add this of their own accord?
2. If django-robots is used, does it come with intelligent defaults?

**Comment by msamoylov** [comment]
1. Well, it's just nice to have and it seems to be better than a static file. I've been using it for 3-4 years and include  it in every public project.
2. It allows everything by default, so your website is accessible.

```
User-agent: *
Allow: /
```

**Comment by pydanny** [comment]
@msamoylov Thank you so much for your pull request. It is very much appreciated.

However, I don't believe this should be integral to Cookiecutter Django. Considering the simplicity of the integration, have you thought about writing a post-generate script to add this to your projects programmatically?

**Pull request closed without merging**
