### PR TITLE
Major refractor to move PYTHON_PATH to top-level repo dir

### LINKED ISSUE #214: Unclear what paths to add to virtualenv
It's not clear to me what paths should be added to the virtualenv. The contents of `setup.py` and `manage.py` seem to contradict each other.

For example, take the following project tree:

```
- repo_name/ # Alias: repo_dir
  - repo_name/ # Alias: project_dir
    - config/
    - manage.py
  - setup.py
```

Should `repo_dir` or `project_dir` be added to the virtualenv?

Given that there was a `setup.py`, I executed `pip install -e .` in `repo_dir`, and it added `repo_dir` as an egg link to my virtualenv. It also added `manage.py` as a script, so I could call it from anywhere - in theory, because it doesn't work from anywhere but `project_dir`.

This is because `manage.py` set `DJANGO_SETTINGS_MODULE` to `config`, which will only work from in `project_dir`. So I guess it should be `project_dir` that must be added to the paths? But what about the `setup.py`?

### PR DESCRIPTION
**Pull request by theskumar**
- PYTHON_PATH now should point to `root_dir` instead of `apps_dir`
- `manage.py` now lives at the root dir
- `config` is moved out to root dir
- We have now a new directory `config/settings`
- root_url is moved to `config/urls.py`
- `wsgi.py` now resides at `config/wsgi.py`

New Structure, after the project is generated:

```
├── config
│   └── settings
├── docs
├── myproject
│   ├── contrib
│   │   └── sites
│   │       └── migrations
│   ├── static
│   │   ├── css
│   │   ├── fonts
│   │   ├── images
│   │   ├── js
│   │   └── sass
│   ├── templates
│   │   ├── account
│   │   ├── avatar
│   │   ├── pages
│   │   └── users
│   └── users
│       └── migrations
└── requirements
```
```
├── CONTRIBUTORS.txt
├── Gruntfile.js
├── LICENSE.rst
├── Procfile
├── README.rst
├── Vagrantfile
├── config
│   ├── __init__.py
│   ├── settings
│   │   ├── __init__.py
│   │   ├── common.py
│   │   ├── local.py
│   │   └── production.py
│   ├── urls.py
│   └── wsgi.py
├── docs
│   ├── Makefile
│   ├── ...
│   └── make.bat
├── install_os_dependencies.sh
├── install_python_dependencies.sh
├── manage.py
├── myproject
│   ├── __init__.py
│   ├── contrib
│   │   ├── __init__.py
│   │   └── sites
│   │       ├── __init__.py
│   │       └── migrations/
│   ├── static
│   │   ├── css
│   │   │   └── project.css
│   │   ├── fonts
│   │   ├── images
│   │   │   └── favicon.ico
│   │   ├── js
│   │   │   └── project.js
│   │   └── sass
│   │       └── project.scss
│   ├── templates
│   │   ├── 404.html
│   │   ├── 500.html
│   │   ├── account
│   │   │   ├── base.html
│   │   │   ├── ...
│   │   │   └── verified_email_required.html
│   │   ├── avatar
│   │   │   ├── add.html
│   │   │   ├── ...
│   │   │   └── confirm_delete.html
│   │   ├── base.html
│   │   ├── pages
│   │   │   ├── about.html
│   │   │   └── home.html
│   │   └── users
│   │       ├── user_detail.html
│   │       ├── user_form.html
│   │       └── user_list.html
│   └── users
│       ├── __init__.py
│       ├── admin.py
│       ├── forms.py
│       ├── migrations/
│       ├── models.py
│       ├── urls.py
│       └── views.py
├── package.json
├── requirements
│   ├── base.txt
│   ├── local.txt
│   ├── production.txt
│   └── test.txt
├── requirements.apt
├── requirements.txt
└── setup.cfg
```
This is second PR for #220 

closes #214 

(Work in Progress)

### CODE REVIEW

**Comment by pydanny** [comment]
Looks great! Amazing work! I've tested it and it appears to work. Want me to merge it in?

**Comment by theskumar** [comment]
I tested it locally, and all seems to work fine too. I was about to test the wsgi.py by deploying to Heroku, then I had to leave for some work. I'll test the heroku deployment and merge it myself.

**Comment by theskumar** [comment]
Btw. If you happened to test it on heroku, please merged it in! :)

**Comment by theskumar** [comment]
This is PR is not tested against heroku deployment. There were issues[1], unrelated to this PR, which were first resolved in `master` and this PR is rebased version of `master`. 

Merging this PR in! 

[1] https://github.com/pydanny/cookiecutter-django/compare/e0e6d8a8ea9c...0cc9958635c

**Pull request merged**
