### PR TITLE
Fixed S3 HTTP URL for /static and /media storages

### LINKED ISSUE #1337: Bug report: Setting up a different AWS S3 region in production.py
I work out of Nairobi, so I set up a Digital Ocean "droplet" in London and wanted my ```static``` and ```media``` files hosted in London as well.

The default settings for AWS s3 are:

`STATIC_URL = 'https://s3.amazonaws.com/%s/static/' % AWS_STORAGE_BUCKET_NAME`
   and
`MEDIA_URL = 'https://s3.amazonaws.com/%s/media/' % AWS_STORAGE_BUCKET_NAME`

These settings would produce a static url for a web site favicon image of 
    `s3.amazonaws.com/staticstore.example/static/images/favicon.ico`
where `staticstore.example` is the ```AWS_STORAGE_BUCKET_NAME``` environment variable.

After a number of unsuccessful tries [ like 2 days :-( ], I went to my s3 console and found out that my favicon is being served from s3 in Europe(London) with the "s3.eu-west-2.amazonaws.com/staticstore.example/static/images/favicon.ico" url.

To replicate:
I did 3 things:

1. Created a new vanilla cookiecutter-django project, built it with the ```local.yml``` and made sure it has its "static" and "media" files are being served. 
2. In ```production.py```, I changed the following settings:

     ```
     ...
     MEDIA_URL = 'https://s3.eu-west-2.amazonaws.com/%s/media/' % AWS_STORAGE_BUCKET_NAME
    
     # Static Assets
     # ------------------------
    
     STATIC_URL = 'https://s3.eu-west-2.amazonaws.com/%s/static/' % AWS_STORAGE_BUCKET_NAME
     ...
    ```

3. I built a new s3 bucket whose only change was region set to "EU(London)". I built a new user and created an s3 policy and attached the new user to the s3 bucket.

I destroyed the droplet and built a new one using the changed ```production.yml```. Using the ```docker-compose -f production.yml up``` command, I could see all the static files being copied to my new bucket.

Expected behavior:
On running the website, only django html appeared and all the static files were not served. On checking it out, I found that the ```{% static 'images/favicon.ico ' %}``` was converted to ```https://s3.amazonaws.com/staticstore.example/static/images/favicon.ico``` and yet I expected ```https://s3.eu-west-2.amazonaws.com/staticstore.example/static/images/favicon.ico```

While I can not see where the bug would come from if ```settings.MEDIA_URL``` and ```settings.STATIC_URL``` were being processed by Django properly, the only other option is the ```storages.backends.s3boto3``` was not reading the ```production.py``` configurations but making up its own default url based on some rule.

Can anybody else confirm this?

### PR DESCRIPTION
**Pull request by umrashrf**
## Description

Fixing a bug

## Rationale

It's broken

## Use case(s) / visualization(s)

N/A

## Edit

Closes #1337
Closes #1711

### CODE REVIEW

**Comment by webyneter** [comment]
Why do you think it's broken?

**Comment by umrashrf** [comment]
Ok for some reason they seem to work on my current project. But a few weeks ago I had a problem. So I am going to close it until I can reproduce it again.

**Comment by browniebroke** [comment]
It looks like the URL we use currently [might not work if you choose a region other than US East (N. Virginia)](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro)

> in a path-style URL, the bucket name is not part of the domain (unless you use a Region-specific endpoint). For example:
> * US East (N. Virginia) Region endpoint, http://s3.amazonaws.com/bucket
> * Region-specific endpoint, http://s3-aws-region.amazonaws.com/bucket

**Comment by umrashrf** [comment]
Ah that makes sense as few weeks ago my project hosted under ca-central-1 and now I am using us-east-1.

**Comment by browniebroke** [comment]
Thanks for the contribution :tada:

**Comment by browniebroke** [comment]
I just found out today!

**Pull request merged**
