### PR TITLE
Add newrelic for monitoring.

### PR DESCRIPTION
**Pull request by amjith**
Please use this PR as a starting point for addressing https://github.com/pydanny/cookiecutter-django/issues/353. 

I have not tested this since I don't have various credentials (AWS keys) required to setup a production instance of the generated app. 

This PR also doesn't add logging for the newrelic agent because the [logging setup for sentry](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/config/settings/production.py#L167) seems to override everything else, which will have to change.

### CODE REVIEW

**Comment by jayfk** [comment]
thanks!

**Comment by amjith** [comment]
flake8 check is failing because of extra blank lines. But the extra blank lines are introduced by the template system when the `if` conditions are false. I'm not sure what's the workaround for it.

**Comment by audreyr** [comment]
@amjith You can use Jinja2's whitespace control: http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

**Comment by burhan** [comment]
Why not use the [heroku instructions for newrelic](https://docs.newrelic.com/docs/agents/python-agent/getting-started/django-heroku-quick-start)?

**Comment by jayfk** [comment]
> Why not use the heroku instructions for newrelic?

That's a heroku specific thing that only works on heroku.

**Comment by amjith** [comment]
The PR is made flake8 compliant. Sorry about the delay, I'm in India visiting family so computer time is limited.

Tests are passing. But I'd prefer if someone tries deploying an app using this template with newrelic enabled. As I mentioned in the original comment, I don't have a production instance to test this with.

**Comment by jayfk** [comment]
Tested, works! Thanks @amjith

**Pull request merged**
