### PR TITLE
Load url tags removed - deprecated in django 1.9

### PR DESCRIPTION
**Pull request by yunti**

### CODE REVIEW

**Comment by luzfcb** [comment]
@yunti thanks. we will probably merge this when Django 1.9 release

**Comment by yunti** [comment]
No problem thanks - I couldn't wait to start using JSONField!

**Comment by pydanny** [comment]
@luzfcb, considering this version of Cookiecutter is for 1.8, is there any reason why we shouldn't just merge it in right now?

**Comment by luzfcb** [comment]
merged. 

Thanks @yunti @pydanny

**Pull request merged**
