### PR TITLE
Update nginx.conf

### PR DESCRIPTION
**Pull request by jangeador**
addresses #807

### CODE REVIEW

**Comment by luzfcb** [comment]
@jangeador thanks.
please, you could also add a editorconfig rule to `*.conf` or `nginx.conf` files in

https://github.com/pydanny/cookiecutter-django/blob/master/.editorconfig

https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.editorconfig

**Comment by jangeador** [comment]
@luzfcb not sure if that is correct. I just followed what was already there. for the .editorconfig file.

**Comment by luzfcb** [comment]
@jangeador please, include same config in https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.editorconfig

said that, LGMT

**Comment by jangeador** [comment]
It's done. Please let me know if you can squash the commits, if you can't we can close this PR and I can send a clean one.

**Comment by jayfk** [comment]
Thanks!

**Pull request merged**
