### PR TITLE
Fixed a bug with escaped spaces in Cache-Control.

### PR DESCRIPTION
**Pull request by ka7eh**
It seems there's a bug in boto that causes spaces in Cache-Control get escaped. (see: https://github.com/boto/boto/issues/2536)
For me, the header for static files rendered as this: 'max-age=604800,%20s-maxage=604800,%20must-revalidate' (under python 3 and django 1.7.7)
Turning the string into bytestring solved the issue for me, though I haven't tested it under other versions of python/django.

### CODE REVIEW

**Comment by theskumar** [comment]
This is strange! Now are are using django-storage-reflux[1][2], just because it has python 3 support for S3. Please confirm that you are facing the issue with django-storage-reflux or not.

Also, if possible, please also an open an issue at https://github.com/jschneier/django-storages/issues. And you can add link to that issue alongside your fix.

__Footnotes__
[1] https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/requirements/production.txt#L6
[2] https://github.com/jschneier/django-storages

**Comment by ka7eh** [comment]
I'm using django-storage-redux. I opened this ticket on the repo:
https://github.com/jschneier/django-storages/issues/47
If you want to merge this, we should add a note so we revert it after the issue is solved either in boto or django-storage-redux.

**Comment by theskumar** [comment]
Thanks, please add the note with link to your issue in your commit and i'm happy to merge this in.

**Comment by ka7eh** [comment]
Updates the PR. Good to go!

**Comment by theskumar** [comment]
Thanks! Merging in.

**Comment by theskumar** [comment]
@ka7eh there seemed to be issue while using `str.encode` in python2. I've used `six.b` to resolve the python2/3 compatibility. 

```
if PY3:
    def b(s):
        return s.encode("latin-1")
else:
    def b(s):
        return s
```

**Comment by ka7eh** [comment]
Glad you caught that. As I mentioned, I hadn't tested it on other versions. Thanks

**Pull request merged**
