### PR TITLE
An small pythonic approach to password

### PR DESCRIPTION
**Pull request by sebastian-code**
Providing a more pythonic line for password generation using for that the string content, as suggested for the documentation in #949.

### CODE REVIEW

**Comment by pydanny** [comment]
Could you add the missing `import string` to your pull request? 😉

**Comment by sebastian-code** [comment]
Sorry for that, I totally forgot about it. Done.

**Comment by pydanny** [comment]
Thanks @sebastian-code!

**Comment by Parbhat** [comment]
@pydanny @sebastian-code This is generating `invalid` string. Because this will also include `'` and `"` in the string. I am getting `invalid syntax` as generated string is `'T0ONher2hoM\FoUVJ'[HZaS}:1u\%c(P>X-GaN/iWql!B^f+E}'`. May be that's why earlier `allowed_chars` did not include quotation marks.

**Comment by pydanny** [comment]
Thanks for spotting that error @Parbhat. I removed single and double quotes from that function, as well as back-slashes (the possibility of weird edge cases worries me).

**Comment by Parbhat** [comment]
Great. Docs also need the updates https://github.com/pydanny/cookiecutter-django/commit/e4d1f4dae6460188402db4ba0c0bfbd9abfcdad1

**Comment by sebastian-code** [comment]
Actually that was previously included in the docs. Take a look to #949

**Pull request merged**
