### PR TITLE
Following up on Node.JS + docker-compose = ♥ (#1128)

### LINKED ISSUE #1204: docker-compose up static files cannot be found by wsgi nor nginx
Steps to reproduce:
Using the docker CE in windows, version Version 17.03.1-ce-win12 

1. create a project using this template whitenoise=n, docker=y, windows=y, pycharm=y, postgres=9.6,js_task_runner=none,celery=y, opbeat=n, sentry=n, timezone=America/Panama, mailhog=n, heroku=n
2. rename env.example to .env
3. docker-compose build
4. docker-compose up

Static fields are not served, collectstatic is working and copies files to the destination dir
however only templates are served.

### PR DESCRIPTION
**Pull request by webyneter**
## Problem
Static assets are not available in production.

## Cause
Static assets don't exist in the project's `static/build` given the stack is run with production configuration immediately after project generation.

## Solution
Make sure static assets are built by the time `docker-compose build` gets invoked. 
I see two ways to ensure that:

1. (the easiest, least invasive one) [Document](https://cookiecutter-django.readthedocs.io/en/latest/deployment-with-docker.html) the preliminary step of running the `node` service from development configuration prior to moving to production stage (`build`, `up` etc.):
```shell
docker-compose - f local.yml run -d node
# Wait for build to complete.
# Remove the container afterwards.
```
1. (clean, but presumptive of Docker version) Opt out for [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) with the `node`'s Dockerfile essentially included in the `django`'s Dockerfile as a preliminary build stage; however, for this to work out one of the latest (+17.05) versions of Docker must be running on host machine which might not be the case for the majority of hosts out there for now. 

I personally vote for the first option due to its implementation straightforwardness and ease of maintenance. @jayfk what do you think?

## TODO
* [ ] Disable `node`-powered gulp if grunt was selected (in fact, the whole changeset must be "reverted" i.e. extra files removed and template artifacts not generated).
* [ ] (???) #1228.
* [x] Account for #1227.
* [x] Account for #1257.
* [ ] <s>Upgrade `node` to the latest (pinned) `slim` version.</s>
* Make sure docs are updated:
    * [ ] the project README;
    * [ ] Node.JS-Docker workflow guides.

Closes #1204.

### CODE REVIEW

**Comment by bluesurfer** [comment]
@webyneter 

What kind of benefits brings node.js w.r.t. the previous production setup? I'm just curious.

**Comment by webyneter** [comment]
@bluesurfer, none: I've realized the real problem is that static assets are not available to `django` image on its build phase (since at the `django` image build stage we copy the contents of the project dir to the image file system while in dev setup the assets are built by `node` *after* all the images are built and are accessed by `django` through the `/app` volume mapping available both to `django` and `node`).

**Comment by webyneter** [comment]
@bluesurfer, for now the only way to fix this seamlessly is to ensure static assets are *already* compiled before running `docker-compose build`, so they can then be copied to `django` during build.

However, this is an ugly workaround in the long-run, and I/we have yet to come up with minimally invasive solution to this (I guess, the concept of Docker Compose pre-build actions should be further explored.) 

@pydanny, @jayfk what do you think?

**Comment by webyneter** [comment]
@bluesurfer, @chopanpma, I am rolling back my yesterday's #1128 PR which led to this issue.

**Comment by webyneter** [comment]
The upcoming changes are to succeed those introduced in #1128.

**Comment by badri** [comment]
hi @webyneter. What's the current status of this PR? Why are the commits in https://github.com/pydanny/cookiecutter-django/pull/1128 reverted back? I think that's the way to compile static assets before deploying to production. It eliminates the need to have all node + node related dependencies in the dev env. Let me know if anything can be done from my end.

**Comment by webyneter** [comment]
@badri,

> I think that's the way to compile static assets before deploying to production. It eliminates the need to have all node + node related dependencies in the dev env.

what do you mean?

**Comment by ArcadiaLandTrust** [comment]
Hello @webyneter et al, I'm wondering if the gulp/docker-compose project is still in the works? I'd really love to try it on my current project. If it is not being incorporated, do you have any tips or links for setting it up manually? Would it be safe to copy your setup from before the reversion? 

Thanks and I appreciate all your hard work, really inspiring!

**Comment by webyneter** [comment]
@ArcadiaLandTrust, it's been a while since I last checked out on this, but I hope I will have some time to spare in the coming weeks to review things out here.

To put things into perspective, the initial PR [#1128](https://github.com/pydanny/cookiecutter-django/pull/1128) introducing Docker Compose + Node.JS integration caused static assets not being available in production. As of now, this PR has been far behind `master` for quite some time. 

However, you can still try and integrate Node.JS with your setup by means of:
1. scaffolding a new project with cookiecutter-django;
2. adding/editing project files added/edited over the course of [#1128](https://github.com/pydanny/cookiecutter-django/pull/1128).
3. see how it works alltogether, especially when `docker-compose -f production.yml up` (it will fail but why wouldn't it, though? :)
4. fix the problem either by
4.1. resisting the temptation of running `docker-compose -f production.yml up` ever again, lol (well, actually, unless this PR is resolved :), or
4.2. ensure static assets are created prior to having your production up-n-running every time you need to.

That's how I see it. Ones again, it's been a while since I last worked on this one...

**Comment by ArcadiaLandTrust** [comment]
@webyneter Thanks so much for the thoughtful reply!

**Comment by browniebroke** [comment]
I'm going to close this now that #1687 is merged. We might want to reuse some work from here, but I don't think there is much point in keeping it open.

**Pull request closed without merging**
