### PR TITLE
Use tox and pytest cookies

### PR DESCRIPTION
**Pull request by hackebrot**
This PR changes the test-suite to use [tox](https://pypi.python.org/pypi/tox/) to easily manage test dependencies.

More importantly I converted the tests from using **unittest** to **pytest** along with [pytest-cookies](https://github.com/hackebrot/pytest-cookies) (A pytest-plugin wrapping the [Cookiecutter](https://github.com/audreyr/cookiecutter) API that takes care of figuring out the path to the rendered project etc.)

I wrote docs on how to run the suite using tox in ``CONTRIBUTING.rst`` (#399).

Please let me know your thoughts! Thanks :bow:

### CODE REVIEW

**Comment by pydanny** [comment]
This is an AWESOME pull request! :ship:

**Comment by hackebrot** [comment]
Cool :smile_cat: Thanks you @pydanny

**Comment by luzfcb** [comment]
Cool :smiley_cat: :+1: Thanks @hackebrot

**Comment by jayfk** [comment]
Yeah! This looks really cool :+1:

**Pull request merged**
