### PR TITLE
updates docker-compose format to version 2 #483

### PR DESCRIPTION
**Pull request by aeikenberry**

### CODE REVIEW

**Comment by aeikenberry** [comment]
Darn. Looking at why the test fails.

**Comment by jayfk** [comment]
:+1: 

The test probably fails because travis isn't using docker 1.10 yet.

Adding this to `before_install` should do the trick:

    - sudo apt-get update
    - sudo apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine=1.10.1-0~trusty

**Comment by aeikenberry** [comment]
:100: Thanks that fixed it.

**Comment by jayfk** [comment]
Thanks!

**Pull request merged**
