### PR TITLE
Move div class unquote outside the if tag

### PR DESCRIPTION
**Pull request by jvanbrug**

### CODE REVIEW

**Comment by luzfcb** [comment]
@jvanbrug Thanks. :smile_cat:

**Comment by jvanbrug** [comment]
Thanks! I just read CONTRIBUTING - should I add myself to CONTRIBUTORS?

**Comment by luzfcb** [comment]
don't worry, I'm already doing it.

**Comment by luzfcb** [comment]
:ship: via https://github.com/pydanny/cookiecutter-django/commit/1d9e0960bc4e689658f12907b33f01dc350251e4 :smiley: :dancers:

**Comment by jvanbrug** [comment]
:sunglasses: :+1:

**Pull request merged**
