### PR TITLE
Multicontainer support for Beanstalk

### PR DESCRIPTION
**Pull request by philippeluickx**
Requires heavy testing still

### CODE REVIEW

**Comment by pydanny** [comment]
This looks pretty awesome!

**Comment by pydanny** [comment]
I wish things had worked out differently, but in order to reduce our maintenance burden, elastic beanstalk support was removed per #1417.

However, if you want to create a maintained Elastic Beanstalk fork of this project, I would be honored to link to it from our README.

**Comment by philippeluickx** [comment]
That's a totally understandable decision. Will rebase my fork and send you a PR on the README.

**Comment by philippeluickx** [comment]
@pydanny I put a clean fork up with Multicontainer EBS support: https://github.com/philippeluickx/cookiecutter-django/tree/elasticbeanstalk

Shouldn't be too hard to rebase regularly, as most of the changes are just code added (barely anything removed or changed). Feel free to add a link where appropriate.

**Comment by nhbravo** [comment]
Is there any way to reopen this and rebase it to the new features? Or else, does anybody have a tutorial to make a full deployment to AWS Elastic Beanstalk using multi container with the current version?

**Pull request closed without merging**
