### PR TITLE
read the env, so the env works

### PR DESCRIPTION
**Pull request by spoutnik16**
Spend a whole afternoon tryin to make it works after reading your book... that was the solution to the first problem...

### CODE REVIEW

**Comment by pydanny** [comment]
Solution to what problem?

**Comment by pydanny** [comment]
Looks like django-environ changed the API. Thanks for the catch.

**Comment by jayfk** [comment]
Merging this breaks the docker setup, because the `.env` file is not copied into the image.

The `.env` file was intended to be used only by docker-compose to set up the environment during the build phase.

**Comment by pydanny** [comment]
Oops. I forgot about that detail. I'll look more carefully at the API change and implement the fix.

**Pull request merged**
