### PR TITLE
Rename Dockerfile-dev to Dockerfile-local

### LINKED ISSUE #1256: Rename Dockerfile-dev to local.Dockerfile
That would promote consistency further (for instance, see #1226).

### PR DESCRIPTION
**Pull request by sfdye**
This would make Dockerfile naming consistent with `local.txt`, `local.py` and `local.yml`.

Fixes #1256

### CODE REVIEW

**Comment by webyneter** [comment]
👍

**Comment by webyneter** [comment]
@sfdye and don't forget to add yourself to `CONTRIBUTORS.rst`!

**Comment by webyneter** [comment]
@sfdye you can make this change in this PR as well.

**Comment by sfdye** [comment]
@webyneter Thanks, done!

**Pull request merged**
