### PR TITLE
add new django1.8 template configurations in common.py settings file

### PR DESCRIPTION
**Pull request by luzfcb**
please NOT merge. Waiting django-allauth v0.20.0 release

if you want test this, please install django-allauth directly from master

```
pip install -e git://github.com/pennersr/django-allauth.git#egg=django-allauth -U
```

### CODE REVIEW

**Comment by luzfcb** [comment]
@pydanny @theskumar review me plz

**Comment by theskumar** [comment]
@luzfcb this looks good to me. And I trust you for it's actual working. 

Question: Does django-allauth upgrades is compulsory requirement for this PR?

**Comment by luzfcb** [comment]
@theskumar yes, is compulsory. I tested  from django-allauth master branch only, and everything seemed to work fine.

I can suppose that 0.19.1 work also after applying this patch https://github.com/pennersr/django-allauth/commit/b1bce45012a808aef233e7f7b60a956d8a2524ee

however, I think it's good to wait to version 0.20.0.

the master is far enough from 0.19.1:
https://github.com/pennersr/django-allauth/compare/0.19.1...master

**Comment by theskumar** [comment]
ok it makes sense.

**Comment by pydanny** [comment]
<3 this PR. Can't wait for it to be merged in. :-)

**Comment by eriol** [comment]
It seems django-allauth 0.20.0 was released today! :dancer:

**Comment by luzfcb** [comment]
Thanks @eriol

**Comment by theskumar** [comment]
:heart:

**Pull request merged**
