### PR TITLE
[proposal] Cookiecutter option to introduce `domain` app

### PR DESCRIPTION
**Pull request by webyneter**
The option allows the user to utilize DDD: If confirmed, a `domain` package will be created in apps dir, and referenced in `./config/settings/base.py`.

### CODE REVIEW

**Comment by pydanny** [comment]
I'm curious: How does adding a (mostly) empty app called `domain` turn this into a Domain-Driven design project?

**Comment by webyneter** [comment]
@pydanny, you're right, it doesn't, but it still might be considered a first step towards DDD, saving up on a few keystrokes (just a few indeed, but still :).

**Comment by pydanny** [comment]
Upon reflection, I think adding this is a bit out of scope. That said, how about one or more of the following:

* Create a separate script that adds this tooling outside of Cookiecutter Django.
* Add documentation of this technique to a pull request to Cookiecutter Django.

What do you think?

**Comment by webyneter** [comment]
@pydanny, I agree, that would be a handy addition -- I'm gonna elaborate on that as soon as I can.

**Comment by pydanny** [comment]
I'm going to close this, as its a documentaton issue, not a code thing.

**Pull request closed without merging**
