### PR TITLE
Traefik - Also redirect www. to service.

### PR DESCRIPTION
**Pull request by sorasful**
[//]: # (Thank you for helping us out: your efforts mean great deal to the project and the community as a whole!)

[//]: # (Before you proceed:)

[//]: # (1. Make sure to add yourself to `CONTRIBUTORS.rst` through this PR provided you're contributing here for the first time)
[//]: # (2. Don't forget to update the `docs/` presuming others would benefit from a concise description of whatever that you're proposing)

## Description
I've recently tried to deploy my own project and noticed that some browsers like Google Chrome, Firefox or other redirect automatically when you type www.YOURDOMAIN, I believe they ignore the www and go directly to http://YOURDOMAIN or https://YOURDOMAIN. 
But for other browsers like IE for instance, if you go to www.YOURDOMAIN, you will get an certificate insecure error because www.YOURDOMAIN doesn't match the rule.

[//]: # (What's it you're proposing?)

To add an exception for www subdomain in traefik rules.

## Rationale

[//]: # (Why does the project need that?)

More compatibility with browsers and people often try to access www.YOURDOMAIN .

### CODE REVIEW

**Comment by wadkar** [comment]
Super useful, ended up manually adding it.

**Comment by browniebroke** [comment]
Thanks for your contribution 🎉

**Comment by wadkar** [comment]
Rare, but in case you end up entering sudomains instead of domain name during the cookiecutter prompts, say `domain_name: "api.mydomain.com"` you will get an extra `www.api.mydomain.com` level routing. Maybe a low priority issue can be added to patch this PR so that the additional `www` rule is added when the host has just one `.` character?

**Comment by browniebroke** [comment]
Good point 🤔 

> the host has just one `.` character

That wouldn't work for TLD with 2 parts, for example `.co.uk`...

**Comment by wadkar** [comment]
Good point as well 🤔

I have created a PR where we can discuss possible solutions. Unless we want to revert this PR?

**Pull request merged**
