### PR TITLE
Production settings typo

### PR DESCRIPTION
**Pull request by yunti**

### CODE REVIEW

**Comment by yunti** [comment]
(testing basic pull request before submitting more)

**Comment by luzfcb** [comment]
@yunti please add your name and github username to https://github.com/pydanny/cookiecutter-django/blob/master/CONTRIBUTORS.txt

**Comment by yunti** [comment]
I've added my name to the contributors list.   Thanks.

**Comment by luzfcb** [comment]
@yunti Thanks :ship: :+1:

**Pull request merged**
