### PR TITLE
Add automatic migrations to heroku deploys

### PR DESCRIPTION
**Pull request by yunti**
heroku now has a new feature for running tasks as part of deployment. Perfect for automatic migrations.
https://devcenter.heroku.com/articles/release-phase#specifying-release-phase-tasks

### CODE REVIEW

**Comment by browniebroke** [comment]
I think it's a good addition. However, I think we should also update the docs, we don't need to mention migrations in this page:

https://github.com/pydanny/cookiecutter-django/blob/master/docs/deployment-on-heroku.rst#L50

**Comment by yunti** [comment]
Done see #1955

**Comment by browniebroke** [comment]
Can you please add it to this same pull request? There is no need to create a new one...

**Comment by browniebroke** [comment]
...Alternatively, you can directly edit the file on the right branch in the Github UI:

https://github.com/yunti/cookiecutter-django/edit/patch-7/docs/deployment-on-heroku.rst

**Comment by yunti** [comment]
Thanks, I didn’t manage to move the other git before you.  Thanks for finishing it off

**Pull request merged**
