### PR TITLE
Reflect Celery taskapp refactoring in the docs

### PR DESCRIPTION
**Pull request by jayfk**
Fixes https://github.com/pydanny/cookiecutter-django/issues/279

### CODE REVIEW

**Comment by pydanny** [comment]
LGTM. Anyone else?

**Comment by jayfk** [comment]
@mwdiers might want to take a look on it. I'm still not entirely sure how celery import magic works in the background, but it should do for now.

**Comment by mwdiers** [comment]
Hmm. This doesn't seem right to me. There is really no import magic going on that I am aware of. Celery will look for the named module in the PYTHONPATH, just like any other import.

If the project_root has been added to your PYTHONPATH, then your start command is just this:

```
celery -A taskapp worker -l info
```

**Comment by mwdiers** [comment]
Perhaps I am misunderstanding Two Scoops recommendations, but I never add the repository root to my PYTHONPATH. Only the project root. Obviously, it one adds the repository_root instead, then the proposed doc change is correct.

**Comment by pydanny** [comment]
@mwdiers, we aren't super-explicit in TSD18 where one should set the Python path. We do provide it as a tip for users who know their operating system well enough to get it right, but that's not everyone (for example, it's rather poorly documented for Windows users).

Tell you what, if this turns out not to be super-ideal, we'll refactor and improve the celery part(s) of cookiecutter-django. :smile:

**Pull request merged**
