### PR TITLE
Fix Celery ports error on local Docker

### LINKED ISSUE #3240: Celery ports issues on local docker
when deploying locally on docker. i got this error

`services.celeryworker.ports must be a list`
`services.celerybeat.ports must be a list`

### Fix
removed `ports: []` from `celerybeat` and `celeryworker` in `local.yml`

### PR DESCRIPTION
**Pull request by professorhaseeb**
Fix #3240

### CODE REVIEW

**Comment by browniebroke** [comment]
Thanks 🎉

**Comment by luzfcb** [comment]
@browniebroke this configuration is probably will fail because now we have 3 containers exposing the 8000 port and docker does not allow it

**Comment by luzfcb** [comment]
Issue confirmed. 
@professorhaseeb Thank you for your effort to contribute to this project, but I will have to reverse this pull-request because of the aforementioned issues.

image
****

**Comment by browniebroke** [comment]
Damn, good catch 😞 Regular reminder for me to not merge things too quickly...

**Pull request merged**
