### PR TITLE
Mailhog as docker-container

### PR DESCRIPTION
**Pull request by noisy**
I created this PR, because I don't like the idea, that I have to download additional binaries:

from https://github.com/pydanny/cookiecutter-django/blob/master/docs/developing-locally.rst

> In development you can (optionally) use MailHog for email testing. MailHog is built with Go so there are no dependencies. To use MailHog:
> 
> Download the latest release for your operating system
> Rename the executable to mailhog and copy it to the root of your project directory
> Make sure it is executable (e.g. chmod +x mailhog)
> 

I think it is also better to not use grunt for running mailhog, and because also there are plans to [make grunt optional](https://github.com/pydanny/cookiecutter-django/issues/476) (https://github.com/pydanny/cookiecutter-django/issues/476), this will remove unnecessary dependency

### CODE REVIEW

**Comment by mjsisley** [comment]
+1 for using this in master. I am using this in development and it works well. 

One thing is that if docker is going to be an option (per #516) , maybe all of the changes you made should also check if docker has been selected so that if someone elects to use mailhog and doesn't elect to use docker, they still can use mailhog the old way.

**Comment by jayfk** [comment]
LGTM. Could you do a proper rebase?

**Comment by noisy** [comment]
@jayfk rebased
@mjsisley I have added use_docker guards...

...but I am wondering what we should do if someone will choose:

    "use_mailhog": "y",
    "use_docker": "n",
    "use_grunt": "n",

**Comment by burhan** [comment]
Grunt is not really a requirement here; its just there to facilitate running jobs and can easily be replaced with a `README` note.

Regarding the requirement for using docker, again I feel documentation can handle this.

**Comment by noisy** [comment]
@burhan 
> Regarding the requirement for using docker, again I feel documentation can handle this.

I am not sure, what you mean by that. Should I add something to documentation?

**Comment by jayfk** [comment]
> I am not sure, what you mean by that. Should I add something to documentation?

I think a small hint what to do when using mailhog w/o grunt/docker should be enough.

**Comment by pydanny** [comment]
Should we merge this in and then document it shortly? I would love to see this added.

**Comment by shireenrao** [comment]
This is would be a really nice enhancement. Let me know If I can help out in anyway to get this added.

**Pull request merged**
