### PR TITLE
Add all internal IPs for multiple docker networks

### PR DESCRIPTION
**Pull request by flyudvik**
When developing with modified docker-compose.yml that contains multiple
network definitions, all networks gateways of the created container
should be added to INTERNAL_IPS, otherwise Django-Debug-Toolbar will not
work.

### CODE REVIEW

**Comment by webyneter** [comment]
@flyudvik would you be so kind as to present us with your version of `docker-compose.yml`? I've never worked with multiple Docker subners as well and would gladly examine the sample.

**Comment by flyudvik** [comment]
@webyneter yeah, sure

`version: '3'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  django: &django
    build:
        context: ..
        dockerfile: docker-files/web_application_renamed/Dockerfile
    image: custom_image_renamed
    ports:
      - "8000:8000"
    networks:  # do not use depends_on and links 
      - back-tier
      - front-tier
    environment:
      - USE_DOCKER=yes
    env_file: development.env
    command: /runserver.sh

  postgres:
    build: ../docker-files/postgresql/
    image: postgres
    networks:
      - back-tier
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file: development.env

  redis:
    image: redis:3
    networks:
      - back-tier

networks:
  back-tier:
  front-tier:
`

**Comment by webyneter** [comment]
@flyudvik would you then use `front-tier` for something like `node` service running NodeJS in development for live reload, for instance? Am I thinking the right direction?

**Comment by flyudvik** [comment]
Yeah, it is a stripped version of the docker-compose file that I use, it has rabbitmq, some legacy type ampq workers, and other microservice systems that are used in back-tier, and some for front-tier. And on test server uses modified configuration with overrides with nginx attached to the front-tier network.

**Comment by webyneter** [comment]
@flyudvik does network-level isoltation bring any viable improvements to your setup or could you possibly go on wihout one?

**Comment by webyneter** [comment]
@flyudvik as this is the first time you contribute could you please add yourself to `CONTRIBUTORS`?

**Comment by flyudvik** [comment]
Ok, thank you. @webyneter

**Pull request merged**
