### PR TITLE
Major Project Generation Cleanup

### PR DESCRIPTION
**Pull request by jayfk**
This is a major cleanup regarding project generation. 

It introduces four new `cookiecutter.json` options:

| option  | default  |
|---|---|
| use_docker  |  yes |
| use_heroku  |  no |
| use_grunt  |  no |
| use_angular | no |

## Option use_docker
If docker isn't going to be used it removes:
  - dev.yml
  - docker-compose.yml
  - .dockerignore
  - compose/

Furthermore, it displays a warning during project generation if docker and mailhog/grunt are selected. Both options are not implemented, yet.

## Option use_heroku
If heroku isn't going to be used it removes:
  - app.json
  - Procfile
  - requirements.txt (discuss?)
  - runtime.txt

## Option use_grunt
If grunt isn't going to be used it removes:
  - Gruntfile.js
  - package.json

## Option use_angular
Removes `ng-app` and the `angular` block in `templates/base.html` if angular isn't going to be used.

## Random String Generation

Instead of failing with an absurd error message that the `django` config can't be imported if no pseudo-random number generator is available, it now warns the user to change the `SECRET_KEY`.

## OS Dependencies

Moved `install_os_dependencies.sh`, `install_python_dependencies.sh` and `requirements.apt` into `utiliy/`.

Addresses:
 - [#476: Make Grunt optional?](https://github.com/pydanny/cookiecutter-django/issues/476)
 - [#474: Make Docker and Heroku cookiecutter.json options?](https://github.com/pydanny/cookiecutter-django/issues/474)
 - [#439: Consideration: Move all config files to a specific location](https://github.com/pydanny/cookiecutter-django/issues/439)
 - [#310: Grunt support for docker (partly by displaying a warning)](https://github.com/pydanny/cookiecutter-django/issues/310)
 - [#308: Consider removal of dev.yml](https://github.com/pydanny/cookiecutter-django/issues/308)
 - [#307: Make Angular.js an option, rather than a default](https://github.com/pydanny/cookiecutter-django/issues/307)
 - [#475: Shouldn't the dockerfile take care of installing mailhog? (partly by displaying a warning)](https://github.com/pydanny/cookiecutter-django/issues/475)

### CODE REVIEW

**Comment by Afrowave** [comment]
Very nice. For us, Docker users, that makes a tighter project file/folder. Thank you.

**Comment by luzfcb** [comment]
@jayfk LGTM . thanks

probably it would be good to update the README (https://github.com/pydanny/cookiecutter-django#features) and
https://github.com/pydanny/cookiecutter-django/blob/master/tests/test_cookiecutter_generation.py#L17-L26

**Comment by pydanny** [comment]
There is so much to love about this pull request. :heart:

**Comment by audreyr** [comment]
This is great @jayfk! 

You might want to update http://cookiecutter-django.readthedocs.org/en/latest/project-generation-options.html as well. 

But in the meantime I will go ahead and merge because this is a lot of cleanup that improves the project nicely.

**Comment by djch** [comment]
I tried setting up a new project with this branch yesterday and noticed that Grunt and MailHog are both optional now but the MailHog implementation actually requires Grunt, I think.

Hopefully I have that right and it was worth mentioning here...

**Comment by jayfk** [comment]
> You might want to update http://cookiecutter-django.readthedocs.org/en/latest/project-generation-options.html as well.

Right!



> I tried setting up a new project with this branch yesterday and noticed that Grunt and MailHog are both optional now but the MailHog implementation actually requires Grunt, I think.

Yeah, but grunt wasn't really a requirement for mailhog. It was more like a convenient way to start it, just like the live reloading feature.

**Comment by audreyr** [comment]
I've updated the usage section of README to reflect this.

**Pull request merged**
