### PR TITLE
Added vagrant support with automatic provisioning of dependencies and PostgreSQL

### PR DESCRIPTION
**Pull request by javipalanca**
I've added a Vagrantfile that allows developers to automatically run a vagrant image (utopic64) wich is provisioned with all dependencies (os and python), creates a virtualenv and installs PostgreSQL with the default database for local development.
It also installs python3. I've updated libtiff4-dev to libtiff5-dev. I had to comment gevent since it is not python3 compatible.
Hope this helps!

### CODE REVIEW

**Comment by pydanny** [comment]
Sorry @javipalanca for the slow response. 

In any case, is there any reason to use this when there is docker? Note that I'm not opposed, just asking the question. :smile:

**Comment by javipalanca** [comment]
Hi Danny!
My only reason is that I've not learned docker yet... :=)
btw, does docker run in osx?

**Comment by pydanny** [comment]
Hi @javipalanca! Yes, docker runs very nicely on OSX. I'm using docker-machine and docker-compose and it's very elegant and quick. Our instructions for it in the README aren't quite there yet, something I plan to address in the next few days.

What's nice is besides one small flag I can literally use the same commands locally for provisioning new virtualboxes as I do on Digital Ocean. I don't ever remember having that superpower with Vagrant.

**Comment by pydanny** [comment]
@javipalanca I'm going to go ahead and close this PR. If you think it should get in, let's talk. We always welcome contributions and I don't want to dissuade from making more in the future.

**Comment by javipalanca** [comment]
Hi @pydanny,
Don't worry. I understand. I'm not dissuaded from making more contributions ;-)
In fact, I'm going to learn Docker!

**Pull request closed without merging**
