### PR TITLE
Setup bumpversion

### PR DESCRIPTION
**Pull request by webyneter**
- Create `use_bumpversion` cookiecutter option.
- Require `bumpversion==0.5.3` locally.
- Refactor version resolution in `./docs/conf.py`: Now, there's a single 'source of truth', the `release` variable representing 'the full version, including alpha/beta/rc tags', allowing the `version` to be derived dynamically from itself.
- Provide bumpversion config file pinpointing project version in `./package.json` (the `version` attribute), `./{{cookiecutter.project_slug}}/__init__.py` (the `__version__` variable), and ./docs/conf.py (the `release` variable).

*N.B. The whole point of refactoring `./docs/conf.py` was indeed to faciilitate seamless version bumping.*

### CODE REVIEW

**Comment by webyneter** [comment]
For [now](https://github.com/peritus/bumpversion/issues/128), `bumpversion` lacks full-fledged support for pre-releases (as semver prescribes). I've come up with a trivial workaround (still, not abiding to semver to the utmost extent) working in a following manner:

`0.1.0` →
`bumpversion pre`→ `0.1.0-1.0` →
`bumpversion prenum` → `0.1.0-1.1` →
`bumpversion prenum` → `0.1.0-1.2` →
`bumpversion major` → `1.0.0`.

**Comment by luzfcb** [comment]
Apparently, `bumpversion` has [no active maintainer](https://github.com/peritus/bumpversion/pull/58#issuecomment-289579102) in it since 2015.
To my understanding, we should avoid using it, due to the first rule: https://github.com/pydanny/cookiecutter-django#constraints

That said, there is this fork https://github.com/c4urself/bump2version but I've never used it.

**Comment by webyneter** [comment]
@luzfcb, I see, you're right. I'm closing the PR.

**Comment by luzfcb** [comment]
I am +1 to add any actively maintained library and that does something similar to bumpversion and a minimum documentation of how to use.

**Pull request closed without merging**
