### PR TITLE
Fix for issue #574

### PR DESCRIPTION
**Pull request by kappataumu**
Fix for issue #574

### CODE REVIEW

**Comment by pydanny** [comment]
Can you fix the tests so this can be merged in?

**Comment by jayfk** [comment]
Tests are failing because of the flake8 thing. Should be good.

**Comment by kappataumu** [comment]
@pydanny Sorry, I've been away for a few days. Like @jayfk said, #634 took care of the hiccup.

**Comment by jayfk** [comment]
Thanks! :)

**Pull request merged**
