### PR TITLE
Add tota11y to base.html

### PR DESCRIPTION
**Pull request by ad-m**
Hello,

I suggest add tota11y to base.html. It's toolbar like ```django-debug-toolbar```, but for accessibility. tota11y helps visualize how site performs with assistive technologies.
Caring for people with disabilities is important and should be a standard feature in producing high quality websites, so it is advisable to provide the tools that support this process.

### CODE REVIEW

**Comment by jayfk** [comment]
This is good. But please include it as an asset that can be loaded from the filesystem.

+1

**Comment by ad-m** [comment]
@jayfk: I can't. I do not know enough JS tools (Grunt / gulp).

**Comment by webyneter** [comment]
@jayfk is there a reason that lib cannot be loaded dynamically?

**Comment by jayfk** [comment]
@webyneter I think it's a good practice in general. GitHub can go down, the content can change etc.

**Comment by ad-m** [comment]
@jayfk , the content can't change. This pin to specific commit on GitHub, not master. CDN caches it too.

**Comment by jayfk** [comment]
> @jayfk , the content can't change. This pin to specific commit on GitHub, not master. CDN caches it too.

If the user deletes his account, the repo is free to be taken over. Sure it's just a CSS file that's only served in debug mode, but including it as an asset doesn't hurt.

https://www.theregister.co.uk/2018/02/10/github_account_name_reuse/

I'm going to close this PR but feel free to reopen it and include the file as an asset.

**Pull request closed without merging**
