### PR TITLE
#667 Newline Madness

### PR DESCRIPTION
**Pull request by nelsonlho**
Got rid of base.txt unnecessary newlines

### CODE REVIEW

**Comment by aleprovencio** [comment]
Thanks for helping me with https://github.com/pydanny/cookiecutter-django/issues/667, I guess you're on the right path. I've noticed some points:
* The "Bleeding edge django" line is messed
* There's also work alike to do on the other requirements files

**Comment by pydanny** [comment]
Glad to see you here @nelsonlho! Let me know if you need any help with getting this pull request to pass the tests. 😄

**Comment by aleprovencio** [comment]
Hello @nelsonlho, you have plans to keep playing with this PR?

**Comment by ssteinerx** [comment]
This is failing at this:

Invalid requirement: 'wheel==0.29.0# Bleeding edge Django'

With the bad line in local requirements file.

**Comment by ssteinerx** [comment]
@jayfk Please kill this.

**Comment by jayfk** [comment]
Hey @nelsonlho,

You can run tests locally, take a look at: https://github.com/pydanny/cookiecutter-django/blob/master/CONTRIBUTING.rst#testing

I'm going to close this for now, but you are welcome to create a new PR once all tests pass.

**Pull request closed without merging**
