### PR TITLE
Update black to 19.3b0

### PR DESCRIPTION
**Pull request by browniebroke**
This PR updates [black](https://pypi.org/project/black) from **18.9b0** to **19.3b0**.

---
*Running the bot with an API key allows it to query pyup.io's API for changelogs and insecure packages. This is highly recommended for production use. [Learn More](https://pyup.io/docs/api-key/)*

### CODE REVIEW

**Comment by chr1s3sw0rthy** [comment]
Im having trouble locating black==19.3b0.

(acuity_env) chrisesworthy@penguin:~/code/Acuity/acuity$ pip install black==19.3b0
Collecting black==19.3b0
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement black==19.3b0 (from versions: )
No matching distribution found for black==19.3b0

**Comment by browniebroke** [comment]
What's your version of pip? `pip --version`

**Comment by browniebroke** [comment]
And what's your python version as well?

**Comment by chr1s3sw0rthy** [comment]
3.5.3

Just seeing that the update works with 3.6. So I installed 3.7.2 and
managed to jack up the whole thing. Not your fault.

**Pull request merged**
