### PR TITLE
Install ps on the nginx container and fix docker-compose.yml when using letsencrypt

### PR DESCRIPTION
**Pull request by jangeador**
The file docker-compose.yml ends up with the port option defined twice when using letsencrypt. The arrangement of the if statements in the PR fixes that issue.

The file `start.sh` in the nginx compose folder has the command `kill $(ps aux | grep 'nginx' | grep -v 'grep' | awk '{print $2}')`. The problem is that the `ps` command is not installed in the nginx image. The command added in the PR installs the `ps` command so that `start.sh` runs without error.

This eliminates a problem that I was having where nginx was reporting that port `80` was already in use. The error in the logs was:

```
nginx_1         | /start.sh: 59: /start.sh: ps: not found
nginx_1         | /start.sh: 59: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
nginx_1         | kill -l [exitstatus]
nginx_1         | 2017/05/04 16:20:08 [emerg] 26#26: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx_1         | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
```

### CODE REVIEW

**Comment by ashishnitinpatil** [comment]
The `RUN` command addition works for me.

**Comment by luzfcb** [comment]
LGMT

**Comment by jangeador** [comment]
@luzfcb can we get this merged?

**Comment by jayfk** [comment]
Thanks! This is a needed fix. I don't know how long it will last, though: #1132

**Comment by jangeador** [comment]
@jayfk I have never used Caddy, but so far every decision made by this community has been accurate. Looking forward to adopt it if the community goes that way. Thanks for the merge.

**Pull request merged**
